name: atgt_vn
publish_to: 'none'
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter: { sdk: flutter }
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  geolocator: ^13.0.1
  flutter_tts: ^4.0.2
  permission_handler: ^11.3.1
  http: ^1.2.2
  provider: ^6.1.2
  geodesy: ^1.1.0
  intl: ^0.19.0
flutter:
  uses-material-design: true
